### ISSUE TITLE
[Bug] When reducing the number of back-ups, delete extra back-up.

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12562]
###### Reproduction Steps

0. check in ~/ankidroid/backup that you have N back-ups.
1. open settings > advanced > max number of back-ups.
2. Lower the numbers to N-2
3. confirm those new settings, close them normally, etc...
4. Go to ~/ankidroid/backup

###### Expected Result

There should be N-2 back-ups

###### Actual Result

There are N bakc-ups.

**Comment by dae** [comment]
In the new schema path, thinning happens each time a new backup is created.

**Comment by mikehardy** [comment]
Interesting @dae - but what if the user does not want to create a new backup, yet wants to reduce storage consumption by lowering backup count. If I were that user I would have the expectation it would thin the backups immediately without rotating an extra slot via creating a new backup right then.

Is there a new schema way to do thin without creating a new backup?

**Comment by dae** [comment]
There's no separate API to just do the thinning, but I was not entirely accurate in my last statement: thinning happens each time you call createBackup(), which if force=false, will not create a new backup unless it's time for one.

**Comment by Arthur-Milchior** [comment]
For the context, Android requires us to create an activity offering the user to save space. So I guess adding a `createBackup` call should solve the issue after the number of back-up was reduced.
I guess it'll okay if the feature only start working when we have the new back-up

**Comment by mikehardy** [comment]
Sounds like createBackup + force=false is perfect after the user selects the quantity they desire
If it *does* create a backup, it was time anyway, that seems acceptable to me
Either way, old backups are thinned and space is as user requested

**Comment by xidsyed** [comment]
I had a few questions regarding the code, which I thought it best to ask you:
1. The `Collection` is more than abstraction to 'talk' to the backend library, correct? What broadly is the responsibility held by `Collection` vs the `Backend`
2. Anki has a Collection and a `CollectionV16` and TagsV16, MediaV16... What exactly is the difference. 
3. Does the original `Collection` still exist only because the implementation has not been completely moved over to V16?

And finally, I was confused regarding the 2 ways of creating and thinning backups, 
1. Within the anki package in `BackupManager.performBackup` and 
2. another in the External Anki Library.

Both of these get used in the `DeckPicker`. Why is that?

**Comment by xidsyed** [comment]
Here are the 2 methods that I am talking about

I found one place where the 'thinning' takes place when performing new backups. `performBackups` function 
https://github.com/ankidroid/Anki-Android/blob/8f602ec6a8fe379456c37055116d92f5baa0cc76/AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt#L156
which gets called from the `DeckPicker.onFinishedStartup()`
https://github.com/ankidroid/Anki-Android/blob/8f602ec6a8fe379456c37055116d92f5baa0cc76/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L1045 

but this is different from the `createBackup(force: Boolean)` you have been talking about 

> Sounds like createBackup + force=false is perfect after the user selects the quantity they desire If it _does_ create a backup, it was time anyway, that seems acceptable to me Either way, old backups are thinned and space is as user requested

Which is a `DeckPicker` Extension Function
https://github.com/ankidroid/Anki-Android/blob/8f602ec6a8fe379456c37055116d92f5baa0cc76/AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt#L31

which calls the `backend.createBackup()` but from the `CollectionV16` instance. and is implemented in the Anki-Android-Backend Library

**Comment by mikehardy** [comment]
You might examine https://github.com/ankidroid/Anki-Android-Backend to see how we talk to the actual sqlite database now

We're in the process of delegating even more of the logic to the underlying / shared backend library (written in Rust, used in all other clients) and that's the V16 stuff you see.

It's a fairly delicate + important process to migrate, a bit like changing drivers in a moving car, so it is proceeding at a measured pace. However, in settings --> advanced you can turn on "new schema support" (which if you look at the code means that you'll fall into the "legacy schema" conditional branches) and with that you may access v3 scheduler as well as backend-provided translations and even some of the desktop's user interface elements (via exposing the built typescript pages etc).

Hopefully that clears up with there are 2 of things in play at the same time.

**Comment by xidsyed** [comment]
So ... `newSchema == newBackend == CollectionV16` right?
thanks, that explains a lot. But I still dont understand, why the 2 different methods for creating and thinning backups. Do they correspond to the old and new schema way of doing things?

I tried calling `createBackup` with force = false. It does create a new backup if its time, but does not delete the older files.

Plus the "Max number of Backups" option goes away, if I turn on the "new schema support"!!
NOW I'm really confused 😂.

**Comment by mikehardy** [comment]
Strange. I was under the impression that with the new schema we could still manage the number of backups. For instance, turn on new schema and go to system preferences -> ankidroid app info -> storage -> manage space

There should be options there to manage backups? That's a different activity / way to access this functionality but if I remember my testing, it works. So perhaps the functionality needs to be abstracted (if not abstracted) and reused in this area for new schema

**Comment by xidsyed** [comment]
Yes, in the code the visibility is set to `!usingNewBackend`. So whenever new backend is being used, the option to limit max backups goes away. at the same time, just below all the options for daily/weekly/monthly backups are visible when the opposite is true, i.e. new schema is being used.
https://github.com/ankidroid/Anki-Android/blob/8f602ec6a8fe379456c37055116d92f5baa0cc76/AnkiDroid/src/main/java/com/ichi2/anki/ui/preferences/screens/BackupLimitsPresenter.kt#L173

Any idea why that is the case?

**Comment by xidsyed** [comment]
Here's a simple working solution for the time-being I came up with, could you take a look at it? https://github.com/xidsyed/Anki-Android/commit/0495e8cec009b389fa52358098ec57955a83f3ff

**Comment by dae** [comment]
Perhaps the backups you have were created within 2 days - only files older than that are subject to thinning.

**Comment by xidsyed** [comment]
Is that why the max number of backups option is removed in new schema? and is replaced by daily/weekly/monthly to keep

**Comment by KratikaTugnawat** [comment]
i want to work on this issues please assign me this issue

**Comment by MudssirAhmed** [comment]
Hey, @Arthur-Milchior, I start working on this issue, If possible you can assign it to me

**Comment by TanmayAgarwal123** [comment]
I would love to work on this project, can you assign me
Regards,
Tanmay Agarwal

**Comment by dae** [comment]
Closing in favor of #14366
