### ISSUE TITLE
[Bug] Import almost never works AND export fails.

### ISSUE THREAD

**Issue by JamesAM86** [ankidroid/Anki-Android#13033]
Hi there,

For a long time, my app has greatly struggled to import decks. I have just been trying to import a well-known and oft-used deck to learn Chinese and after a 7+hour wait it was on 52% cards imported and 0% on the other metrics...

Then I got the usual error message along the lines of "AnkiDroid has encountered an problem; sending message to Developers".

I also cannot export my AnkiDroid collection. It simply says the export has failed after a very long wait when I then select "Send" or "Save as file"...

Below is the debug info from my app; would you be able to help me with this or advise a little?

Thanks in advance!
James

DEBUG INFO:

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-A405FN

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A405FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 6f0a4e54-ee6a-4cf8-ac3d-6daf502efe22

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by criticalAY** [comment]
Hey! Thanks for logging the issue please try out the latest alpha[https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha92] release

**Comment by JamesAM86** [comment]
> Hey! Thanks for logging the issue please try out the latest [alpha](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha92) release

Thanks for the tip. This didn't work, unfortunately. Instead the import was slow and then the pap just stopped responding and went to a black screen.

**Comment by criticalAY** [comment]
Could you link the deck? I would like to reproduce it

**Comment by criticalAY** [comment]
And did you send the report?

**Comment by JamesAM86** [comment]
> Could you link the deck or name it here? I would like to reproduce it

By all means. :) There are actually two doing this right now, but I have found many do the same. In the order I am trying to upload:

HSK1-4 Listening, Reading and Writing Deck - AnkiWeb
https://ankiweb.net/shared/info/1474834583

HSK 3.0: Learn Mandarin Chinese by drawing strokes [HSK 1-9] - AnkiWeb
https://ankiweb.net/shared/info/536858343

**Comment by criticalAY** [comment]
If possible please report the crash so that we can look at the stacktrace

**Comment by criticalAY** [comment]
Update : it works fine on the latest built and most probably is fixed maybe you will have to wait for the next alpha

**Comment by JamesAM86** [comment]
> Update : it works fine on the latest built and most probably is fixed maybe you will have to wait for the next alpha

Thank you so much for testing that out! Also yes, my app must have sent dozens of reports...

So there is currently no way to work around this it seems - would you by any chance have an indication of when the next alpha might be released?

**Comment by JamesAM86** [comment]
> Update : it works fine on the latest built and most probably is fixed maybe you will have to wait for the next alpha

Apologies, now I cannot even open decks. :/  Is there a way to revert to the previous version?

**Comment by criticalAY** [comment]
umm around 2-3 weeks

**Comment by JamesAM86** [comment]
Hey there,

My apologies!

Unfortunately, the error is still occurring and I've yet to find a solution.

I will make a note in the ticketed question.

Many thanks
James
