### ISSUE TITLE
[BUG]: New Cards Don’t Appear in Correct Order

### ISSUE THREAD

**Issue by Chicchaikoneko** [ankidroid/Anki-Android#14026]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Hello there,

Previously I posted this issue on the AnkiWeb forums: https://forums.ankiweb.net/t/bug-new-cards-dont-appear-in-correct-order/27719

Basically, when I use both Ankidroid and Anki desktop alongside each other, syncing from Ankidroid messes up the new card review order of any new cards subsequently added from Anki desktop. You can refer to the above link for more details.

### Expected behaviour

New cards should come up for review in sequential order.

### Actual behaviour

Every time I sync with Ankidroid, the order of new cards subsequentially added is messed up and not sequential from the previous new cards. 

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = samsung

Model = SM-A326U1

Hardware = mt6853

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A326U1 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.130 Mobile Safari/537.36

ACRA UUID = 8ffe1f11-b546-4d53-9798-754fb882648d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Thanks, and my humble apologies if somebody has already posted this issue (I did try to search through and couldn't find anyone reporting this issue though).

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
Please try the latest beta release and switch on the new backend in advanced settings. The issue should be resolved there.
[https://github.com/ankidroid/Anki-Android/releases/tag/v2.16.0beta3](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16.0beta3)

**Comment by mikehardy** [comment]
going to close this pre-emptively as I'm 99% this will be fixed by using the latest release, but of course we can/will reopen if you test the latest release and there are still issues...

**Comment by harrisonmg** [comment]
In case it's useful information to anybody, I experienced an identical issue (mentioned in #9298) and switching to the V3 scheduler seems to have fixed it.

**Comment by Chicchaikoneko** [comment]
> In case it's useful information to anybody, I experienced an identical issue (mentioned in #9298) and switching to the V3 scheduler seems to have fixed it.

Thanks for the tip. I tried this but it doesn't seem to work for me. In Anki on PC, I went to preferences and changed to v3 scheduler. Is there a setting that needs to be changed in Ankidroid on mobile too? After changing to v3 scheduler in Anki desktop, I'm still getting new cards added in the wrong order (i.e. number is lower than ones added before them).

Also, when is the latest release coming out? Can I get it on the Play Store?

**Comment by mikehardy** [comment]
I see this as the version in the original issue details:

> AnkiDroid Version = 2.15.6

So it is not possible to use the V3 scheduler in the 2.15.6 version (the v3 scheduler did not exist then! :-) )

If you get the new 2.16.0beta versions (here are a variety of ways listed: #13797 in the workaround section) then you will have "new backend" and "v3 scheduler" options in the advanced preferences.

And then...I hope it works 🤞
