### ISSUE TITLE
[BUG] Storage permission is asked in Android 13 and can't be granted [F-Droid/Full]

### ISSUE THREAD

**Issue by alexanderadam** [ankidroid/Anki-Android#15463]
### Checked for duplicates?

- [X] This issue is not a duplicate (_well, in my opinion it is but [I'm just following here](https://github.com/ankidroid/Anki-Android/issues/14423#issuecomment-1935079369)_)

### What are the steps to reproduce this bug?

It's exactly the same issue as mentioned in #14423 but [I was asked to open a separate issue](https://github.com/ankidroid/Anki-Android/issues/14423#issuecomment-1935079369). :shrug: 

### Expected behaviour

It complains with the message "Please grant AnkiDroid the storage permission" which unfortunately can't be given

### Actual behaviour

Anki already has the permissions for

- Read and write to the AnkiDroid database
- Microphone
- Notifications

but it wants _moooore_ :wink: 

### Debug info

```text
I can't even open the app so how should I provide this information? :wink:
```

### (Optional) Anything else you want to share?

And how do other apps access data if Anki isn't allowed to do it any more?  
For instance [the Video player NOVA](https://github.com/nova-video-player/aos-AVP/) can access data from various paths. And the same is true for [VLC player](https://code.videolan.org/videolan/vlc-android) of course.

Furthermore I have PDF viewers and other document apps that can access files.  
What's the difference here? 🤔

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
What version of the app are you using?

The permission (which has been fixed in 2.17) is `all files access`

On my phone, this is either searchable, or:

* Settings
* Apps
* Permission manager
* Files
* See more apps that can access all files

**Comment by alexanderadam** [comment]
> What version of the app are you using?
> 
> The permission (which has been fixed in 2.17)

That might be the culprit here as [the latest version on F-Droid is 2.16.5](https://f-droid.org/de/packages/com.ichi2.anki/#latest).

**Comment by david-allison** [comment]
The steps provided should work for 2.16.5

**Comment by alexanderadam** [comment]
I followed [the mentioned flow](https://github.com/ankidroid/Anki-Android/issues/15463#issuecomment-1935087805) and gave the permission. I killed AnkiDroid even afterwards but it still shows the error toast and redirects to the 'wrong' permission dialogue.

**Comment by david-allison** [comment]
What version of Android are you on?

**Comment by alexanderadam** [comment]
Android 13
Samsung One UI 5.1

**Comment by soshial** [comment]
I have the same problem on Samsung Galaxy S22 with Android 14 with the latest F-Droid v2.16.5.

**Comment by david-allison** [comment]
@soshial Any issues with the 'full' build of the 2.17beta?

**Comment by soshial** [comment]
Thanks, @david-allison! `AnkiDroid-2.17beta2-full-universal.apk` worked well, it asked for MANAGE_EXTERNAL_STORAGE successfully and I was able to create a test deck and add a card.

Although, I must admit I cannot possibly allow an app having such a grave permission installed on my phone. Do the Google Play and F-Droid versions have this permission removed? Which builds employ [app-specific storage](https://developer.android.com/training/data-storage/app-specific) instead?

**Comment by david-allison** [comment]
The `play` variant (also distributed on Google Play) doesn't request the permission.

F-Droid uses `full`, which requires it.

If you're using `play`, be sure to sync regularly. Without that permission, uninstalling wipes all data and backups from your device

**Comment by AbdullahAhmadAAK** [comment]
I have the same issue on my Samsung Galaxy A32.

**Comment by tasmo** [comment]
Also not possible in Android 14 with GrapheneOS and Fdroid version 2.17.1.
