### ISSUE TITLE
[BUG]: Can't display images with `#` in filenames

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15963]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Add a card including an image file containing `#` (hashtag) in its filename

   ---
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/7ceee40f-9035-4835-9ec4-487dbf08e935" width="320px">

   ---
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/71af16e5-88c5-4512-8bd4-b68bc554ac53" width="320px">

   ---
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/9a364722-6244-4f4e-abbe-64de03f0641f" width="320px">

   ---

3. Show the card in reviewer or previewer

### Expected behaviour

The image is shown, as on 2.16.5.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/e2ee6e08-2485-4261-8978-014ac077d858" width="320px">
(2.16.5)

### Actual behaviour

The broken-image icon is shown, and the image isn't shown.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/4f266193-fc2d-4ae6-a935-f7b0adacc53b" width="320px">

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

- Originally reported in Anki Forum:
https://forums.ankiweb.net/t/ankiweb-and-ankidroid-do-not-display-images-containing-pound-hashtag-sharp-symbol/42444/1
  and dae has commented there.

- As reported there, this issue occurs on AnkiWeb, too. 
   ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c588f585-b23c-4be6-b8f1-8a098a127705)
So, strictly speaking, this is not a bug specific to AnkiDroid, but some approach specific to AnkiDroid may be needed, I'm not sure though.

- This issue doesn't occur on Anki Desktop (as reported in Anki Forum) and on AnkiMobile.
- The `#` is shown as `%23` on the editor of Anki Desktop (as reported in Anki Forum). 
   ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/5ba75763-6007-4668-b036-0cb13e54cdc5)
   > \> Windows changes it back to a # in the sort field, but the HTML text remains unchanged
   >
   > This happens because Anki stores filenames without encoding on disk (legacy reasons), but needs to encode them before they’re shown in the editor.

   (dae)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (2.18alpha6)

**Comment by snowtimeglass** [comment]
It seems to have already been fixed in the current HEAD.

**Comment by krmanik** [comment]
I don't think so, it is ongoing discussion in the PR, https://github.com/ankidroid/Anki-Android/pull/15909#issuecomment-2001940011

**Comment by snowtimeglass** [comment]
Thank you for the feedback.

Not for objection (since I don't have enough knowledge about the topic), just for rewording more accurately and for what it is worth, the issue seems to have been fixed in my debug version build from a854e93 (Mar 17, 2024).
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/33981165-9b2d-4bb0-bb7a-276fc84036c0" width="320px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/b8df4bd1-1b6e-47f4-ad93-b5d18d65f726" width="320px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/d24c8169-89dd-4238-90db-ab147f0e262d" width="320px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/9dde94fc-0be4-46e6-bee7-7d3da38630b4" width="320px">

**Comment by snowtimeglass** [comment]
On the other hand, adding (creating) a card with the image file adding by Anki Desktop is not shown (i.e. shown as a broken-image icon) even in the debug version of AnkiDroid. In this case, `#` is shown as it is in the browser and the editor.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/5ee6f54f-6443-414d-b3a5-1f71502c244c" width="320px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/19ff3d38-4733-4e49-9199-cb716ce8cc1c" width="320px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/dcfbfca0-f8e1-415d-9147-81851f5dda11" width="320px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ad920e0c-0cc2-49ea-9502-a919f44a53c9" width="320px">

**Comment by BrayanDSO** [comment]
# is a illegal char in HTML, so it’s not supposed to work anywhere if not encoded. Ankidroid encodes it when importing, and AFAIK Anki does it as well.

**Comment by BrayanDSO** [comment]
Read now damien's comment about "legacy reasons", since `#` still isn't supposed to be treated as something else that isn't a URL fragment marker in that context, so this is a deliberate anki breakage of the URL scheme.

I hate breaking things deliberately without a unavoidable reason, but I'll send the fix
