### ISSUE TITLE
[BUG]: TTS ERROR_SERVICE

### ISSUE THREAD

**Issue by carloslme** [ankidroid/Anki-Android#17423]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1.  Sync the cards from the desktop app (MacOS) to the server. The TTS works fine.
2. Sync the Android app from the server.

### Expected behaviour

What happened:
- When the play button is pressed, get the error `Text to speech error (ERROR_SERVICE)` as shown below ![Image](https://github.com/user-attachments/assets/056b7205-6675-4619-9bfe-1ac8c2cfe849)

What should happen:
- The TTS reproduces the audio.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S908E

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S908E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.86 Mobile Safari/537.36

ACRA UUID = 4214263c-3f33-4f02-8709-28da2dd88ae3

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, we've made some changes here in our latest release. 

Could you test in 2.19.1 and see if this still occurs

**Comment by carloslme** [comment]
Still failing. This is the Debug info:
```
AnkiDroid Version = 2.19.1 (6953d60532ee2762d29b06fd1d76e69203ad8455)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = samsung

Model = SM-S908E

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S908E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.86 Mobile Safari/537.36

ACRA UUID = 0f785a2b-de08-41df-9f6e-77961a64875d

FSRS = 0.6.4 (Enabled: true)

Crash Reports Enabled = true
```

Note: I used this Anki Version https://github.com/ankidroid/Anki-Android/releases/download/v2.19.1/AnkiDroid-2.19.1-full-universal.apk

**Comment by david-allison** [comment]
What's the status of your on-device TTS Engine? 

Does this continue to fail if you use Google TTS?

**Comment by carloslme** [comment]
With the new version downloaded from the Play Store, the issue was solved!

**Comment by david-allison** [comment]
Thanks! But I wouldn't expect that it would fix it... what was the version?

I suspect this was another part of Android failing

**Comment by carloslme** [comment]
If it helps, this is the Debug info, but it it is the same as the initial report. Thanks anyway!
````
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S908E

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S908E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Mobile Safari/537.36

ACRA UUID = 7d4aea1d-e444-4b7c-b430-5f92f4afdb5b

FSRS Enabled = true

Crash Reports Enabled = true
````

**Comment by david-resnick** [comment]
Hi, the problem still occurs for me. Should this be reopened, or would you like me to open a new ticket? The TTS hasn't worked for me for about a month.

```
AnkiDroid Version = 2.19.2 (b073f52783583fd4fd1436d986090ced9006a66b)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S926B

Hardware = s5e9945

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S926B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 46de3e1d-44ce-44d0-8e44-c16c6c858a5f

FSRS = 0.6.4 (Enabled: true)

Crash Reports Enabled = true
```

**Comment by david-allison** [comment]
Hi @david-resnick, happy to reopen this one.

Can you test 2.18.4 and see if it works:

https://github.com/ankidroid/Anki-Android/releases/download/v2.18.4/AnkiDroid-2.18.4.parallel.A.apk

**Comment by david-resnick** [comment]
I already got it to work with 2.18.4 😬 

I opened the TTS voices settings page for the first time. Is this only available when adding `{{tts-voices:}}` to a card template?

I tried testing the voice for the language I need, and it failed -- didn't do anything, no error either. It started working after I pushed "reset". It now works normally. I even got the added bonus of changing the TTS engine from Google to Samsung, and that also works. 

To help you find the root cause for the bug, some further info about what I've encountered.

1. TTS started failing some months ago with the same ERROR_SERVICE message. I quickly got it working again after some combination of restarts and opening the Google Translate app to activate the engine.

2. TTS started failing about a month ago, this time after an app upgrade (I recall the changelog screen). Nothing fixed it, including reinstalling, and leaving and rejoining the beta channel in the Play store. I did though tell it to leave local files after uninstalling, so that might be why it continued to fail after reinstall.

The problem even continued after installing on a new Samsung device yesterday, using the Samsung app that transfers all app data from the old phone to the new (something I was expecting would resolve the problem). It must have copied over some bad state from my original phone.

In case this is relevant, the TTS is all done using the `tts` tag, e.g. `{{tts th_TH:Front}}`.

I hope this helps, thank you for all your work on this amazing app!
