### ISSUE TITLE
Card info not displayed for Review cards

### ISSUE THREAD

**Issue by Danika-Dakika** [ankidroid/Anki-Android#17681]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

- From card browser, select a card, open menu [or from study screen, open menu]
- Open Card info

Result: the page loads with the Card Info title at the top, and the back arrow, but no info is displayed. I’ve waited up to a minute and the screen stays blank. It’s the same whether I open Card Info from the card browser or study screen.

### Expected behaviour

Complete card info and review history is displayed.

### Debug info

```text
AnkiDroid Version = 2.20.1 (e32a82c33646807ea19623c9c88be38965bc07e6)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 9 (SDK 28)

ProductFlavor = play

Manufacturer = Amazon

Model = KFONWI

Hardware = mt8168

Webview User Agent = Mozilla/5.0 (Linux; Android 9; KFONWI Build/PS7321; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Safari/537.36

ACRA UUID = 55ae3c0a-d60c-451d-8dfa-6b0426c97b63

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

**For New cards**, the top rows of info display correctly after a short delay. [The delay is maybe 0.5-1 seconds – but I don’t remember whether that was happening previously.]

I upgraded from 2.18.4 (or thereabouts) – skipping 2.19. I’ve run check database, cleared cache, restarted the device. I am not yet using FSRS 5 [waiting to re-optimize until I’m upgraded on desktop] – noting that in case it’s an issue with some of the new Card Info features.

Responding to @david-allison 's requests [in the forums](https://forums.ankiweb.net/t/ankidroid-2-20-changelog/52782/5?u=danika_dakika): 
> Diagnostics would be useful via listing any errors in the JS console: [Development Guide · ankidroid/Anki-Android Wiki · GitHub](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection)

I tried to get this going, and it's showing me the tabs in my device's Chrome browser, but nothing that looks like it could be coming from AnkiDroid. Perhaps I'm missing something obvious? 

> For a fix: see if you can update Android System WebView, it appears to be out of date, and is the likely cause

It's an Amazon FireHD tablet which says it's using _Amazon_ System WebView version `94.amazon-webview-v94-4606-tablet.4606.71.23` -- I assume that's the right thing, but I don't know how those version numbers compare to Android. It doesn't appear to be upgradable (well, possibly with a FireOS update, but I can't allow that or everything else will break -- long story). 

I've found a couple sites [[apkmirror.com](https://www.apkmirror.com/) I know to be reputable, [uptodown.com](https://en.uptodown.com/) I've never heard of] with apk versions of Amazon System WebView I could sideload. I'm hesitant to come all the way up to current -- any speculation as to the minimum version I could update to that might work? 

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Please check if Statistics work. If it is a Webview issue, it should not

**Comment by xjqm-tao** [comment]
I have the same problem.So is the latest version.(2.21alpha4).`AnkiDroid Version = 2.21alpha4 (ce369b478238f93e3a47d7a7f4753729fa934c0c)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true`

**Comment by xjqm-tao** [comment]
I have the same problem.So is the latest version.(2.21alpha4).`AnkiDroid Version = 2.21alpha4 (ce369b478238f93e3a47d7a7f4753729fa934c0c)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true`

**Comment by xjqm-tao** [comment]
> Please check if Statistics work. If it is a Webview issue, it should not

I have the same problem.

**Comment by xjqm-tao** [comment]
I found that my desktop board is the same.

Version is
`
Anki 24.11 (87ccd24e)  
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19041
`

**Comment by Danika-Dakika** [comment]
@BrayanDSO 
Stats looks fine for me. There was a little delay to it loading -- about 2-3 sec -- but the turning semicircle let me know it was coming.

**Comment by david-allison** [comment]
@Danika-Dakika Could you check if this resolves the issue: https://github.com/ankidroid/Anki-Android/issues/17696#issuecomment-2569240069

* Download: https://play.google.com/store/apps/details?id=com.google.android.webview.dev&hl=en
* Enable Android Dev Options
* In Android System Dev options, set 'WebView Implementation'

**Comment by xjqm-tao** [comment]
> [@Danika-Dakika](https://github.com/Danika-Dakika) Could you check if this resolves the issue: [#17696 (comment)](https://github.com/ankidroid/Anki-Android/issues/17696#issuecomment-2569240069)
> 
> * Download: https://play.google.com/store/apps/details?id=com.google.android.webview.dev&hl=en
> * Enable Android Dev Options
> * In Android System Dev options, set 'WebView Implementation'

I don't think webview caused it. My card also appears on the computer.I upload my card and see if you can reproduce it.[https://ac-data.info/d/RlUkcfLmBe0](url)

**Comment by Danika-Dakika** [comment]
@david-allison 
Unfortunately, I can't install that app. Fire OS 7 is based on Android 9 -- https://en.wikipedia.org/wiki/Fire_OS#List_of_Fire_OS_versions. 
![Image](https://github.com/user-attachments/assets/c3c8a14d-eac5-423c-a78b-b7d58f074dc3)

**Comment by chrislongros** [comment]
Could we add Card Info from the reviewer too ? In case users want to see scheduling information while reviewing the specific card.

**Comment by xjqm-tao** [comment]
@david-allison 
I found that I can view the card information normally for the newly added card.

**Comment by david-allison** [comment]
@Danika-Dakika I presume this is still a problem?

**Comment by Danika-Dakika** [comment]
@david-allison @BrayanDSO 
Yes, it's still an issue -- so much so that I've been considering reverting to an earlier version. I use the Card Info often. 

I'm happy to do anything you need to help you track this down, but I'm limited by what's possible on my device and OS. 

I don't know if it's significant, but there were _changes_ to the Card Info display in Anki 24.11, which seems like it doesn't happen frequently. A major one -- the addition of the per-card forgetting-curve graph [ankitects/anki#3437] -- and another -- display the Position [ankitects/anki#3471]. It seems that both of those change the Card Info for a Review card, but not for a New card -- which still works (no data for the forgetting curve, Position was already displayed).

**Comment by BrayanDSO** [comment]
Sorry, I linked the wrong thing. 

Do the steps in https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection then share what you get in the console

**Comment by david-allison** [comment]
Reproduced:

* API 28 emulator (Pixel 8)
* Download and install
  * https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-94-0-4606-71-release/android-system-webview-94-0-4606-71-4-android-apk-download/download/?key=fd289de302d62854e17db84421daee079803ab90&forcebaseapk=true
* Enable FSRS
* Card Info fails

```
Uncaught (in promise) TypeError: s.toReversed is not a function
    at Zt (2.ChVmXzJ3.mjs:1)
    at Qt (2.ChVmXzJ3.mjs:1)
    at 2.ChVmXzJ3.mjs:2
    at vt (runtime.BreniANL.mjs:1)
    at runtime.BreniANL.mjs:1
    at Wt (runtime.BreniANL.mjs:1)
    at $ (runtime.BreniANL.mjs:1)
    at L (runtime.BreniANL.mjs:1)
    at ft (runtime.BreniANL.mjs:1)
    at Dr (runtime.BreniANL.mjs:1)
```

**Comment by david-allison** [comment]
* This is fixed upstream in https://github.com/ankitects/anki/pull/3681

@mikehardy Think it's feasible to pull this in as a patch release for 2.20, given Anki 25.XX might take some time to get over the finish line

**Comment by david-allison** [comment]
@Danika-Dakika For now, the best shout would be to upgrade your Android System WebView. 

I believe it's still actively updated for Android 8

**Comment by xjqm-tao** [comment]
> Reproduced:
> 
> * API 28 emulator (Pixel 8)
> * Download and install
>   
>   * https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-94-0-4606-71-release/android-system-webview-94-0-4606-71-4-android-apk-download/download/?key=fd289de302d62854e17db84421daee079803ab90&forcebaseapk=true
> * Enable FSRS
> * Card Info fails
> 
> ```
> Uncaught (in promise) TypeError: s.toReversed is not a function
>     at Zt (2.ChVmXzJ3.mjs:1)
>     at Qt (2.ChVmXzJ3.mjs:1)
>     at 2.ChVmXzJ3.mjs:2
>     at vt (runtime.BreniANL.mjs:1)
>     at runtime.BreniANL.mjs:1
>     at Wt (runtime.BreniANL.mjs:1)
>     at $ (runtime.BreniANL.mjs:1)
>     at L (runtime.BreniANL.mjs:1)
>     at ft (runtime.BreniANL.mjs:1)
>     at Dr (runtime.BreniANL.mjs:1)
> ```

You inspired me. I installed "AnkiWebView Inspector”Add-ons on the computer.
Open the card information window and see these errors in the console.
`Failed to load resource: the server responded with a status of 404 (NOT FOUND)
2.CfZ3BNlt.mjs:1 Uncaught (in promise) TypeError: s.toReversed is not a function
    at Zt (2.CfZ3BNlt.mjs:1)
    at Qt (2.CfZ3BNlt.mjs:1)
    at 2.CfZ3BNlt.mjs:2
    at vt (runtime.BreniANL.mjs:1)
    at runtime.BreniANL.mjs:1
    at Wt (runtime.BreniANL.mjs:1)
    at $ (runtime.BreniANL.mjs:1)
    at L (runtime.BreniANL.mjs:1)
    at ft (runtime.BreniANL.mjs:1)
    at Dr (runtime.BreniANL.mjs:1)
:9804/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)`

**Comment by david-allison** [comment]
* To be fixed in https://github.com/ankidroid/Anki-Android-Backend/issues/456

**Comment by Danika-Dakika** [comment]
Sorry, I missed some of these updates, but it sounds like it's on the road to fixed, which is great! 

Just to close the loop on these -- 

@BrayanDSO 
> Do the steps in ...
I tried that before my initial post, and I wasn't able to get anything to happen. Probably user error [but also I think you don't need this from me anymore].

@david-allison 
> For now, the best shout would be to upgrade your Android System WebView.
For anyone else having this issue -- that still won't work on a FireOS tablet, because it uses *Amazon* System WebView instead.

**Comment by david-allison** [comment]
@Danika-Dakika 

Can you change the WebView Implementation in the Android Developer Options (tap on Settings - About - build number ~7 times)

**Comment by david-allison** [comment]
* Fixed in https://github.com/ankidroid/Anki-Android/pull/17890

**Comment by david-allison** [comment]
@Danika-Dakika To confirm: you can't install an Android System WebView APK, or you can, and it doesn't appear there

**Comment by Danika-Dakika** [comment]
@david-allison I can't (or at least haven't been able to) install it. The current version is only [compatible with Android 10 and up](https://github.com/ankidroid/Anki-Android/issues/17681#issuecomment-2574233654). 

If there's an earlier Android WebView version that you think would help, that's compatible with my OS, and that we can find from a reputable APK site ... I'm happy to try it.
