### ISSUE TITLE
Regression in new drawing board: gesture conflicts, stylus button not working, drawings disappear

### ISSUE THREAD

**Issue by oit35570-dotcom** [ankidroid/Anki-Android#19846]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Touch input (finger drawing) 

1. Open a card in review or edit mode. 
2. Enable the drawing board. 
3. Try to scroll the card using a two-finger gesture. 
4. Draw something on the card. 
5. Disable the drawing mode. 
6. Enable the drawing mode again. 

Stylus input (S Pen) 

1. Open a card on a device with Samsung S Pen. 
2. Enable the drawing board. 
3. Enable stylus drawing mode. 
4. Draw something on the card. 
5. Press the hardware button on the S Pen to erase part of the drawing. 

### Expected behaviour

Touch input (finger drawing) 

- Two-finger scrolling should work while finger drawing mode is enabled. 
- Drawn objects should persist when toggling the drawing mode off and on. 

Stylus input (S Pen) 

- Pressing the S Pen hardware button should switch to eraser mode, as it did in the old drawing board. 

### Debug info

```text
AnkiDroid Version = 2.23.1 (3f3133b496b531383e9a6494f5a7704634935308)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 16 (SDK 36)  
ProductFlavor = play  
Device Info = samsung | samsung | gts10fewifi | gts10fewifieea | SM-X520 | s5e8855  
Webview User Agent = Mozilla/5.0 (Linux; Android 16; SM-X520 Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Safari/537.36  
ACRA UUID = cee9aa16-ba54-4f69-b925-380857b3dd8a  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true

AnkiDroid Version = 2.23.1 (3f3133b496b531383e9a6494f5a7704634935308)
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)
Android Version = 16 (SDK 36)
ProductFlavor = play
Device Info = samsung | samsung | gts10fewifi | gts10fewifieea | SM-X520 | s5e8855
Webview User Agent = Mozilla/5.0 (Linux; Android 16; SM-X520 Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Safari/537.36
ACRA UUID = cee9aa16-ba54-4f69-b925-380857b3dd8a
FSRS = 5.1.0 (Enabled: true)
Crash Reports Enabled = true
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Ayush-Patel-56** [comment]
I would like to take it up.
Please assign it to me if it’s still available.

**Comment by david-allison** [comment]
I'd give @BrayanDSO final say on allocation here

**Comment by atnoir** [comment]
> I would like to take it up. Please assign it to me if it’s still available.

If possible, in addition to fixing the S Pen eraser issue on the new drawing canvas, I was wondering if you could add Air Actions support—for example, being able to switch between frequently used pen colors? Thanks.

**Comment by david-allison** [comment]
@atnoir Please subscribe to notifications on this issue. I helped write an SDK for us to legally interface with the S Pen, but there hasn't been follow-through yet (and I don't have a Samsung with S Pen to test)
 
* https://github.com/ankidroid/Anki-Android/issues/9670

**Comment by BrayanDSO** [comment]
Should be solved. Now you can assign gestures/keybinds to the whiteboard actions

**Comment by oit35570-dotcom** [comment]
Thank you for the update and for fixing most of the issues with the new drawing board.

After installing the latest version, I can confirm that:

✓ Two-finger scrolling now works in the vertical direction.
✓ Drawings no longer disappear when reopening the drawing board.

However, two issues still remain:

Two-finger scrolling does not work horizontally (only vertical scrolling works). The S Pen hardware button still does not function as an eraser, which worked in the old drawing board. 

Tested on:

Samsung Galaxy S23 (touch input) Samsung Galaxy Tab S10 FE with S Pen 

Please let me know if I should open a separate issue for these remaining problems.

**Comment by david-allison** [comment]
@oit35570-dotcom Thanks! A couple of brief issues would be useful

**Comment by BrayanDSO** [comment]
> Two-finger scrolling does not work horizontally 

old study screen can't do that as well
