### ISSUE TITLE
Again cards number doesn't decrement after studying until getting back to deck page

### ISSUE THREAD

**Issue by mmasaeli** [ankidroid/Anki-Android#3663]
After studying an "again" card, it says I have 0 2 9 card to review (the again counter doesn't decrement). But In fact, I have only 1 other again card to study so it should be (0 1 9). The problem keeps on until I tap on back button (or complete the deck)
![screenshot_2015-09-19-08-22-46](https://cloud.githubusercontent.com/assets/8008472/9978781/7584acd8-5f5d-11e5-9851-b4d78d9453c7.png)
Just taping on the back button shows the real stats (0 1 9):
![screenshot_2015-09-19-08-22-51](https://cloud.githubusercontent.com/assets/8008472/9978782/75d1c8f6-5f5d-11e5-8e9c-e9617be291d4.png)

**Comment by hssm** [comment]
Do you have the widget enabled? Does it go away if you remove it?

If not, can you send me this deck while it is in this state?

**Comment by mmasaeli** [comment]
I'm sorry, I don't know what widget you are talking about.
I'll send you the deck as soon as I face the problem again. BTW, I'm new github, plz tell me how to send a non-image file.
P.S. It's a great work, I love ankidroid and I'll contribute as much as I can as a developer.

**Comment by hssm** [comment]
You can email it to me directly (click on my name to go to the profile page).

**Comment by hssm** [comment]
Sorry for taking my time to get back to you on this. I couldn't reproduce it with the deck you sent me. I may need a copy of the entire collection since it could be related to the creation time of the collection (just a guess).

A couple other questions:
1 - Have you tried using a recent alpha build? If not, can you try to reproduce it using [one of those builds](https://github.com/ankidroid/Anki-Android/releases) so we know it's not something that was fixed along the way? I only tested it with an alpha build myself.
2 - Do you have notifications enabled? Does it go away if you turn them off?

**Comment by kazuoteramoto** [comment]
I can reproduce this when using subdecks. I have the following deck structure
* Parent::SubA
* Parent::SubB

If I study Parent the count in the upper part of the review and in the Parent overview do not get updated, but the count in the deck list get correctly updated. @hssm do you like to me to send my collection?

![1](https://cloud.githubusercontent.com/assets/291287/10647480/655ffce0-7817-11e5-97cb-28841b38eac1.png)

**Comment by kazuoteramoto** [comment]
Forget the part about subdecks, it still happens if a remove the subdecks and make all decks parents.

**Comment by kazuoteramoto** [comment]
Another info (sorry for the spam). The again count increses but don't decrese while reviewing.

**Comment by hssm** [comment]
I'm not sure if this is the same problem described in the opening post. I am aware that the deck list (left) and deck overview (right) have different counts, but does the *reviewer* show different counts from the deck overview? The behaviour shown in your screenshot can also happen on the desktop client under certain conditions.

So, firstly, I need you to test the behaviour on the desktop client and show that it differs in AnkiDroid.

If the behaviour does differ, then please do send me your collection while it is stuck in this state. Also, make a note of the date, time, and time zone on your device while the problem is happening? I will likely need those to be able to reproduce it.

**Comment by kazuoteramoto** [comment]
I'm sorry my problem is really not the same, now I understand the behaviour. Is as you said the intended behaviour, not a bug.

Because I'm using a lot of steps, every time I answer a learning card the again count don't change because its add the next step. This confused me because as as expecting the count in the reviewer to be the due **now** count  not the due **today** count.

**Comment by mmasaeli** [comment]
I'm sorry I have not been around for a while. It appears that the problem is completely fixed in the very lates beta version. In addition, there was no such issue on the desktop version.
Thanks.

**Comment by hssm** [comment]
That's good to hear. Thanks for getting back to us on this.
