### ISSUE TITLE
Bug: the position of the big blue + button (add button) is sometimes too high.

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4217]
![image](https://cloud.githubusercontent.com/assets/10436072/14602648/fedc8112-05a3-11e6-8fb3-9f60e93b399d.png)

**Comment by timrae** [comment]
Steps to reproduce?

**Comment by snowtimeglass** [comment]
Sorry, I still don't know how to do now.

**Comment by snowtimeglass** [comment]
Ah, I got it.

It is displaying a toast message that reproduces it.

![image](https://cloud.githubusercontent.com/assets/10436072/14603451/ab8ab7fe-05a8-11e6-9bf0-7ecf94ed1094.png)

**Comment by timrae** [comment]
I guess you mean a "snack bar". So it doesn't go back down after the snack
bar disappears? Does it happen every time? What device?

**Comment by snowtimeglass** [comment]
You're right. It's a "snack bar".

>So it doesn't go back down after the snack
bar disappears?

No, it doesn't.

>Does it happen every time? 

Yes, it seems to happen every time.

>What device?

Galaxy Note 2
Android version:4.3
AnkiDroid: 2.6alpha22

**Comment by timrae** [comment]
Does the same issue occur on other devices?

**Comment by timrae** [comment]
Also, has it always happened or only recently?

**Comment by snowtimeglass** [comment]
The issue doesn't occur on my tablet device.
(Incidentally, it doesn't occur on AnkiDroid-2.5beta16.parallel.C on Galaxy Note 2, either.)

I noticed this issue recently, so I don't know whether it had always happened before.

**Comment by timrae** [comment]
Please try uninstall reinstall

**Comment by snowtimeglass** [comment]
I uninstalled 2.6alpha22, and installed alpha21.
Then, the issue doesn't happen. In other words, the "+" button goes back down properly after the snack
bar disappears.
However, after updating alpha21 to alpha22 (on Google Play) and displaying a snack bar, the issue always happens.

**Comment by hssm** [comment]
It would have to be a change in the support libraries then. I couldn't reproduce it on an emulator on Android 4.3 though.

**Comment by snowtimeglass** [comment]
@timrae 
>Does the same issue occur on other devices?

@hssm 
>I couldn't reproduce it on an emulator on Android 4.3 though.

The issue can be reproduced on an emulator, "BlueStacks". Its Android version is 4.4.2.

_a video
http://xfs.jp/C8VNe0_

**Comment by timrae** [comment]
Can't access the video, the page is full of spam. Please use Google drive or Dropbox

**Comment by snowtimeglass** [comment]
Certainly.
I'm sorry for the inconvenience.

https://drive.google.com/file/d/0BzcRTIITO8NoSkxWLVlTZzk4WHc/view?usp=sharing

**Comment by timrae** [comment]
Hmmm I couldn't find any bugs matching this description on the AOSP bug tracker... I guess we're going to have reproduce it ourselves and report it, or just roll back the support library to 23.3.1 and wait for someone else to...

**Comment by hssm** [comment]
Looks like this was a side-effect from [another issue](https://code.google.com/p/android/issues/detail?id=206416) which has been fixed in today's release of the support libraries.

**Comment by hssm** [comment]
And would you believe it, Google "fixed" the issue but really didn't :tada: !

I sent them some feedback on the issue tracker but it's likely we aren't getting a fix before we plan to release 2.6. I'll see what their reply is first but I think we'll have to downgrade the design support libs.

**Comment by snowtimeglass** [comment]
>I want to try updating the support libs and see if @snowtimeglass can still reproduce it in the next beta.

("Update support libraries" #4288)

Thank you for the work, but the problem can still be reproduced on my smartphone.

- Galaxy Note 2
- Android version:4.3
- AnkiDroid: 2.6beta2

[video](https://drive.google.com/open?id=0BzcRTIITO8NoMlJmcVRZN1RiZ2c)

On the other hand, on BlueStacks,  the plus button doesn't go up when a snack bar appears.

- Android version:4.4.2
- AnkiDroid: 2.6beta2 (beta1, too)

[video](https://drive.google.com/file/d/0BzcRTIITO8NoSlFRY0tKVHAzanM/view?usp=sharing)



On my tablet, the plus button moves properly on 2.6beta2, as ever.
- Android version:4.1.2

**Comment by hssm** [comment]
Let me know how it works in beta 3.

**Comment by snowtimeglass** [comment]
Now, on 2.6beta3, the problem isn't reproduced on my smartphone. 2.6beta3 works nicely on it. Thank you.

On the other hand, on BlueStacks, the plus button still doesn't go up when a snack bar appears as it doesn't on 2.6beta2 (see [the video](https://github.com/ankidroid/Anki-Android/issues/4217#issuecomment-220014233) above), in contrast to 2.6alpha21 (see [the video](https://github.com/ankidroid/Anki-Android/issues/4217#issuecomment-214402359) above).

**Comment by hssm** [comment]
It seems to be some weird behaviour around animations. Do you have animations disabled on your phone? Do you use Tasker or anything might make use of Accessibility services?

For me the problem is always present when I disable animations, on all versions of the support library that we've tried and on various Android versions.

**Comment by snowtimeglass** [comment]
>Do you have animations disabled on your phone? 

Maybe, I don't.

>Do you use Tasker or anything might make use of Accessibility services?

Yes, I use Tasker on my smartphone.
I don't on BlueStacks though.


>For me the problem is always present when I disable animations, on all versions of the support library that we've tried and on various Android versions.

For me, the problem didn't happen on my smartphone when I used 2.6alpha21.


Thank you anyway. 
I don't mind the behavior on the BlueStacks so much.
How about you?

**Comment by mikehardy** [comment]
With respect :-) I'm closing this as stale, and our support libraries have moved a HUGE amount since then. I have an open issue to change the floating buttons implementation to one that is supported #4936 and by linking that one here I'll make sure to test snack bar behavior. Even if this was a bug at the moment, since it's an interaction between support libraries - system settings - and our floating button implementation, all out of our control at the moment, this is not actionable
