### ISSUE TITLE
Rescheduling doesn't work (?)

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5167]
###### Reproduction Steps

1. Review a card
2. Choose "Scheduling" - "new card plan" (I don't know the English term, I'm using German)
3. Type in new interval xxx days (there is "0/4" written below the text field, what does that mean??) and press OK

###### Expected Result

Card should be re-scheduled and disappear from review screen

###### Actual Result

Card remains in review screen and I need to press one of the 3 answer buttons. So the previously typed in rescheduling interval will be overwritten (probably).

Actually I couldn't check the new interval because AnkiDroid lacks a field for that in the card browser (Anki desktop shows the due date, AnkiDroid not)

So this issue combines 2 things:
1) after scheduling a card during reviews, the card should no longer be seen. Moreover, provide an explanation what that "0/4" below the interval text field means.

2) please provide a field in the card browser (or an entry in the context menu) that shows the current interval/due date for that card.

###### Debug info
AnkiDroid Version = 2.9alpha54

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Interesting! I just wrote this code so I can imagine exactly how this is happening, thanks for writing it up. I'm marking it as needs triage but that's a flag for attention for me, not a bad thing.

The second issue does also seem valid, but it does seem separate to me - could you split it off into a new issue?

**Comment by mikehardy** [comment]
This was a good one - a clear miss for the Reviewer case after all the reschedule work. Thanks for logging it and whenever #5180 is in shape to merge (and then released) this should be resolved.

**Comment by mikehardy** [comment]
@Anthropos888 this is released in the alpha from yesterday if you want to retry it? Should *actually* work now. Thanks again for the testing and taking the time to report things, I appreciate it

**Comment by Anthropos888** [comment]
Works perfectly now, thanks a lot!

**Comment by Anthropos888** [comment]
Btw: the new logo button for "rescheduling" (during reviews) is very nice! Now it's obvious what it means. 
All the "play", "pause" and "rewind" buttons etc. are not quite self-explaining (actually I still don't know what they are doing), so it was nice to see that you made a new button for rescheduling.

**Comment by mikehardy** [comment]
Thanks! I actually hand crafted part of that on svg just to see how svg worked. My first icon :grin:

**Comment by timrae** [comment]
Sorry to hijack this thread, but I'm wondering if perhaps we need to do more to discourage users from abusing this feature? For example some warning the first time encouraging users to "trust the algorithm". I believe @dae consciously didn't  make the manual rescheduling feature visible in the reviewer for this reason, and once we put it in we can't really take it out, so now is probably a good time to consider the risks.

@dae do you have any thoughts on this?

**Comment by Anthropos888** [comment]
Sorry to share my thoughts on this since I'm just a user and not a developer, but as for AnkiDroid, users can't "trust the algorithm".

I have to use re-scheduling every day because AnkiDroid shows me siblings with just one day in between, even though their interval was 1year or even more. That's just a waste of my time reviewing this card. On Anki I use add-ons to prevent this but on AnkiDroid these add-ons have no effect. 

So I'm very glad that I can use the re-scheduler very comfortably now.

**Comment by dae** [comment]
IMHO micromanaging the scheduling is not the most productive use of one's time, but some users wish to do so, and if it's behind a hamburger menu that is probably enough.

**Comment by Anthropos888** [comment]
@mikehardy
I noticed a few things:
1) I normally re-schedule learning/mature cards and it works fine. But today I rescheduled a new card (it uses kanji that I didn't learn learn yet) and typed in 100 days as interval (probably I will have learned the utilized kanji until then).

I checked the re-scheduling in Anki desktop and saw that the card now has an interval (3.3 months) amd is no longer a new card.

I didn't know that. I thought, new cards will still be "new" after re-scheduling. But now I realize that in this case "re-positioning" would have been the correct function to use. 

You see, these feature names are a bit confusing to me (especially with German translation), even though I'm using AnkiDroid since over a year.

After accidentally using re-scheduling I needed to find the cards in the browser, reset the progress, re-position it in AnkiDroid and then use Anki desktop to re-position it again because AnkiDroid doesn't show the position numbers so I had no clue which number to set.

Therefore: a short message "re-scheduling new cards will turn them into mature cards." "OK / Cancel" would be super helpful.
(similar to the error message that is shown when trying to re-position a learning/mature card)

And again: it would be great if "due time/position" would be an extra column to choose for the card browser. Otherwise all re-scheduling and re-positioning tasks are more or less blind.

**Comment by eginhard** [comment]
If you have clearer suggestions for the translations (also in general) you
can add them yourself here:
https://crowdin.com/translate/ankidroid/all/en-de
Let me know if you add any and I can approve them.

**Comment by Anthropos888** [comment]
@eginhard The translations itself are very good but some parts of the re-scheduling feature just got translated recently. So I got confused with the former English terms which are quite different.

**Comment by mikehardy** [comment]
@Anthropos888 I see what you mean on the advisory "reschedule makes cards mature" message. Those are easy at least though I'm a bit occupied at the moment - would you mind creating a separate enhancement request for that? For the "due time/position" card browser column does that already exist as an enhancement request? If not it would make a good one as well - those sorts of things are possible...

**Comment by Anthropos888** [comment]
@mikehardy I opened an issue regarding the due time column already but I don't think I can add the enhancement label myself:
https://github.com/ankidroid/Anki-Android/issues/5168
